#!/usr/bin/env ruby

require 'rbconfig'
require 'zlib'

suffix = case RbConfig::CONFIG['host_os']
         when /linux/
           os_name = `. /etc/os-release 2> /dev/null && echo ${ID}`.strip
           os_version = `. /etc/os-release 2> /dev/null && echo ${VERSION_ID}`.strip

           # CentOS 6 doesn't have `/etc/os-release`.
           if os_name.empty? && File.read('/etc/centos-release').start_with?('CentOS release 6')
             os = 'centos_6'
           elsif os_name == 'fedora' && os_version.to_i >= 29
             os = 'centos_8'
           else
             os = "#{os_name}_#{os_version}"
           end

           architecture = case RbConfig::CONFIG['host_cpu']
           when 'x86_64'
             'amd64'
           when 'arm'
             'armhf'
           else
             'i386'
           end

           "#{os}_#{architecture}"
         when /darwin/
           RbConfig::CONFIG['host_cpu'] == 'x86_64' ? 'macos_cocoa' : 'macos_carbon'
         else
           raise 'Invalid platform. Must be running on linux or intel-based Mac OS.'
         end

basedir = __FILE__.sub(%r{/exe/wkhtmltoimage$}, '')
binary = File.join(basedir, 'lib', 'wkhtmltoimage', 'binaries', suffix, 'wkhtmltoimage')

if !File.exist?(binary) && File.exist?("#{binary}.gz")
  File.open(binary, 'wb', 0o755) do |file|
    Zlib::GzipReader.open("#{binary}.gz") { |gzip| file << gzip.read }
  end
end

unless File.exist?(binary)
  raise 'Invalid platform. Must be running on linux or intel-based Mac OS.'
end

exec *$*.unshift(binary)
